# listen on port 80
entryPoints:
  http:
    address: ":80"

# Traefik dashboard over http
api:
  dashboard: true
  # insecure: true

log:
  level: "DEBUG"

# containers are not discovered automatically
providers:
  docker:
    exposedByDefault: false
