version: "3.6"

services:
  web:
    build: ./app
    expose: 
      - 8000

  nginx:
    build: nginx
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cert:/cert
      - ./nginx:/etc/nginx/conf.d
